---
- hosts: localhost
  gather_facts: true
  
  tasks:
    - name: run multiline shell command
     shell:
        cat /etc/hostname
     register: release
   
    - name: above task success
      shell:
        echo "success"
      when: release.rc == 0
